
server:
  port: 8889


  
spring:
  datasource:
   druid:
    db1:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name : com.mysql.cj.jdbc.Driver
      username: root
      password: root
      jdbc-url: jdbc:mysql://localhost:3306/hxsp?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&zeroDateTimeBehavior=CONVERT_TO_NULL
    #   数据源其他配置
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  main:
    allow-bean-definition-overriding: true
#    mongoDB配置
  data:
    mongodb:
      host: dds-bp1bd27aa60c7de41210-pub.mongodb.rds.aliyuncs.com
      database: xbt_dev
      port: 3717
      username: xbt_dev
      password: Vtnn&tr9ui2

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


  # 配置ehcache缓存
  cache:
    type: ehcache
    # 指定ehcache配置文件路径
    ehcache:
      config: classpath:/ehcache.xml



mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.hxsp.bean
  #分页配置
  ######### 分页插件 ##########
  pagehelper:
    helper-dialect: mysql
    params:
      count: countSql
    # 分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页，pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。
    reasonable: true
    # 支持通过 Mapper 接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
    support-methods-arguments: true



# 设置单个文件最大内存
multipart:
  maxFileSize: 50Mb
# 设置所有文件最大内存
  maxRequestSize: 50Mb
# 自定义文件上传路径
web:
  upload-path: D:/hc/images/
# 显示图片的路径
  image-path: https://hxsp.mynatapp.cc/images/


  ######### 微信支付配置 ##########
wechat:
  mpAppId: wx24892f2be58676dc
  mchId: 1603487065
  mchKey: CsTavJWYGpjv6qBXSb2yZm2Wcojabzhi
  keyPath: /var/weixin_cert/wxpay.p12
  notifyUrl: http://hxsp.mynatapp.cc/hxsp/pay/notify
  miniAppId: wx24892f2be58676dc
  miniAppSecret: bb2e87cefab3001dfdd1bba7d37f5481
  appAppId: